# see https://werkraum.net/devblog/wie-fuege-ich-ckeditor5-plugins-in-typo3-12-ein
editor:
  config:
    importModules:
      - { 'module': '@ckeditor/ckeditor5-code-block', 'exports': [ 'CodeBlock' ] }

    extraPlugins:
      - Code
      - CodeBlock

    toolbar:
      items:
        - code
        - codeBlock

    # see https://prismjs.com/#supported-languages
    codeBlock:
      languages:
        - { language: 'plaintext', label: 'Plain text' }
        - { language: 'php', label: 'PHP', class: 'language-php' }
        - { language: 'sql', label: 'SQL', class: 'language-sql' }
        - { language: 'yaml', label: 'YAML', class: 'language-yaml' }
        - { language: 'json', label: 'JSON', class: 'language-json' }
        - { language: 'css', label: 'CSS', class: 'language-css' }
        - { language: 'scss', label: 'SCSS', class: 'language-scss' }
        - { language: 'javascript', label: 'JavaScript', class: 'language-js' }
        - { language: 'typescript', label: 'TypeScript', class: 'language-js' }
        - { language: 'shell', label: 'Shell', class: 'language-shell' }
        - { language: 'xml', label: 'XML', class: 'language-xml' }
        - { language: 'nginx', label: 'Nginx', class: 'language-nginx' }
        - { language: 'bash', label: 'Bash', class: 'language-bash' }